### ISSUE TITLE
Add ability to save exact version

### ISSUE THREAD

**Issue by bigassdragon** [wesleytodd/create-package-json#2]
This module is really awesome for what it does, I would like to have an enhancement made to allow the user to save the exact versions of their dependancies and dev dependancies.

To do this we would need to use `--save-exact` when we do `npm install --save` and `npm install --save-dev`.

I do not mind making a PR for this feature, just would like to gather your thoughts on this before I made a random PR for something you may not want at the end.

**Comment by wesleytodd** [comment]
Thanks!!  This wounds like a great feature, but the api for I am picutring might be a bit confusing if you wanted to mix pinned and unpinned (which is a common case in my experience).  The other complexity is pinning dev deps vs normal deps.  Do you have any ideas how you would like to see this done?

**Comment by bigassdragon** [comment]
I was thinking of something like `exectDeps` as a boolean and `exactDevDeps` as a boolean. Those two options would then put `--save-exact` in the script for `npm install` so that way the user can control if they want to have exact dependancies installed or not.

**Comment by wesleytodd** [comment]
That is also what I pictured, which is why I brought up the issue of mixed pinned and unpinned.  For example, if you wanted:

```
"dependencies": {
  "somelib": "^1.0.0",
  "pinnedlib": "1.0.0"
}
```

The api presented would not let this happen.   Is there something we can do do avoid this?  What about making the version string for each dep allow for some modifier?  "somelib@1.0.0:exact" as a very bad example of one way.

**Comment by bigassdragon** [comment]
I actually made a fork of this and it does work if you just put `--save-exact` without any changes.

you can do something like this
```
"dependencies": {
  "somelib": "^1.0.0",
  "pinnedlib": "1.0.0",
  "another": "^1.0.x"
}
```

Those examples will still get you the either the latest if you want or exact when you do not have `^` or `x` assigned in there.

**Comment by wesleytodd** [comment]
Ok, so your cli usage to replicate that would be this?

```
create-package-json --dependencies="somelib@^1.0.0,pinnedlib@1.0.0,another@^1.0.x" --save-exact
```

If so, that sounds great!  A PR is welcome.

**Comment by wesleytodd** [comment]
Hey, so I think I added your feature in the new version.  This is almost a complete re-write on top of a package I wrote to help make maintaining these types of packages easier and have better composability.  It would be great if you could give it a try:

`npm i create-package-json@0.0.10`

Let me know if you have any feedback, and feel free to re-open this if I did not get it correct for your use case!

**Comment by bigassdragon** [comment]
Sorry I did not respond, I was out for the holiday.

I will review what you did, when I made the change it was just a config option since I do not use the `cli` at all.

Thanks for the feature request though.

**Comment by wesleytodd** [comment]
No worries!  I was just working on pushing this big refactor, so I figured I would include this new feature in it.  Let me know when you get a chance to test the new version if it works for you!
